sudo: false
language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
scripts:
  - "npm test"
matrix:
  allow_failures:
    - node_js: "5"
    - node_js: "4"
addons:
  sauce_connect: true
after_success:
  - "npm run test:sauce"
